// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MovieApp.Models
{
    [Keyless]
    [Table("category")]
    public partial class category
    {
        public int CategoryId { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string CategoryName { get; set; }
    }
}