// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MovieApp.Models
{
    [Keyless]
    [Table("movie")]
    public partial class movie
    {
        public int MovieId { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string MovieName { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string Category { get; set; }
        [Column(TypeName = "date")]
        public DateTime? MovieYear { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string mov_lang { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string PhotoFileName { get; set; }
    }
}